### ISSUE TITLE
Final Project Feedback

### ISSUE THREAD

**Issue by aespaldi** [IkeyBenz/Social-Media-Bot-Scrapers#3]
Final Project Feedback

Overall 17/ 33 (> 20 Passing):
**Resubmit with tests, documentation, and full details in the blog post to get to a passing grade**

This was a really creative way to both build a graph project and explore interests in Selenium and D3.  I would have preferred you write the graph algorithms from scratch instead of using networkx as this will give you a better understanding.  That said, the project excels in other areas.

- 
- Proposal 1/4
- Code Graph Data structure 3/4
  - Interesting data collection from scraping instagram. 
- Code: Solution 1:  3/4
- Code: Solution 2:  3/4
- Code: Solution 3: 3/4
- Code Documentation 1/4
  - not all methods have docstrings
  - running code requires several installations - which are partially documented in README
- Code Testing 0/4
  - No unit tests or exception handling. This code is VERY volatile and without these protections in place is likely not to be sustainable. 
- Blog / Presentation 3/5
  - Good start and hook - spend more time discussing the parts relevant to this project (the three items you discovered in your graph and the graph algorithms needed for these).

**Comment by IkeyBenz** [comment]
Hello Anne, thank you very much for your in depth feedback.

I have improved the quality of the proposal, increased the number of docstrings in the source code, and included a virtual environment so that you users won't need to install a bunch of packages when they use this.
